baseurl: '/markdown-cv'
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed
plugins:
  - jekyll-font-awesome-sass
font-awesome:
  assets: true
exclude:
  - package.json
  - package-lock.json
  - vendor
  - Gemfile
  - Gefile.lock
  - node_modules
  
